"""
test_js_port.py — the golden-fixture gate for the JS engine port.

SCOPE §2 row 7 requires lever recompute to run client-side in the browser,
with NO Python round-trip. That means the dashboard's JavaScript must
contain a faithful port of the engine (demand -> capacity -> constrain ->
finance). The non-negotiable acceptance criterion (SCOPE.md:238) is that
the JS port reproduce the Python engine EXACTLY for the identity lever set
— a 0-diff against mockups/data.js, the golden fixture generated by
mockups/build_data.py from the real engine.

This module shells out to Node (skipped when node is absent) and asserts:

  1. Identity case — all levers neutral. The JS port fed the embedded
     `const DATA` must produce the golden fixture's scenario outputs
     (summary/monthly/utilization/reconciliation/provenance) to 1e-9.
  2. Representative lever mutation — the SAME lever overrides applied in
     JS (via the port) and in Python (via the real engine) must produce
     identical outputs. This proves the port is a true engine, not a
     delta-clone of the shipped scenario outputs.
  3. pyRound — the JS banker's-rounding helper matches Python's round()
     on the known-divergent float cases.

The JS bodies live in sibling `_js_*.js` files (run by `node <file>`, so
no shell-quoting/escaping can corrupt them) and engine-port.js is dual
browser/CommonJS — it sets window.LEVER_ENGINE in the browser and
module.exports under Node, so this test exercises the exact shipped file.
"""

import json
import os
import shutil
import subprocess
import unittest
from pathlib import Path

import _bootstrap  # noqa: F401

REPO = Path(__file__).resolve().parent.parent
TESTS = Path(__file__).resolve().parent
ENGINE = REPO / "mockups" / "engine-port.js"
DASHBOARD = REPO / "output" / "dashboard.html"
GOLDEN = REPO / "mockups" / "data.js"
NODE = shutil.which("node")

# Float cases known to diverge between JS Math.round and Python round().
_ROUND_CASES = [2584, 2023.5, 3008.125, 3008.135, 0.5, 1.5, 2.5, 3.5, 4.5,
                100, 7.674999999999999, 1.005, 2.675, -2.5, -1.5,
                1234567.891, 10, 0, 99.5, 100.5, 200.5]


def _node(script_file: str, env: dict | None = None) -> subprocess.CompletedProcess:
    """Run `node <script_file>` in the repo with standard env injected."""
    full_env = {
        "ENGINE": str(ENGINE),
        "DASHBOARD": str(DASHBOARD),
        "GOLDEN": str(GOLDEN),
    }
    if env:
        full_env.update(env)
    return subprocess.run(
        ["node", str(TESTS / script_file)],
        capture_output=True,
        text=True,
        cwd=REPO,
        env={**os.environ, **full_env},
        check=False,
    )


def _python_run(code: str) -> str:
    proc = subprocess.run(
        ["python3", "-c", code],
        capture_output=True,
        text=True,
        cwd=REPO,
        env={**os.environ, "PYTHONPATH": str(REPO / "src")},
        check=False,
    )
    if proc.returncode != 0:
        raise AssertionError(f"python failed:\n{proc.stderr}\n{proc.stdout}")
    return proc.stdout


# Python: apply the SAME representative lever mutation and print a JSON
# comparable to the JS port's scenario object.
_PY_MUTATION = r"""
import json
from pathlib import Path
from dataclasses import replace
from sop_integrated_planning import cli, demand as demand_mod, capacity as cap_mod, constrain as con_mod, finance as fin_mod
from sop_integrated_planning.models import ScenarioId
from sop_integrated_planning.dashboard import _scenario_monthly_totals

families, resources = cli._load_or_generate_dataset(Path(%r))
vol = 0.10
hours_override = {r.id: r.monthly_available_hours * 1.05 for r in resources if r.id == 'RES-LINEA'}
mut_families = []
for f in families:
    f2 = replace(f, base_monthly_demand=[d * (1 + vol) for d in f.base_monthly_demand])
    if f.id == 'FAM-DRY':
        f2 = replace(f2, unit_price=f2.unit_price * 1.10, unit_variable_cost=f2.unit_variable_cost * 0.97)
    mut_families.append(f2)
mut_resources = [replace(r, monthly_available_hours=hours_override.get(r.id, r.monthly_available_hours)) for r in resources]

sc = ScenarioId.CONSTRAINED
dl = demand_mod.build_demand_plan(mut_families, sc)
loads = cap_mod.compute_loads(dl, mut_families, mut_resources)
sl = con_mod.build_supply_plan(dl, mut_families, mut_resources, sc)
fl = fin_mod.build_finance_lines(sl, mut_families)
summ = fin_mod.summarize(sc, sl, fl)
by_month = {}
for x in fl:
    b = by_month.setdefault(x.month, {'revenue': 0, 'gross_margin': 0, 'lost_revenue': 0, 'lost_margin': 0})
    b['revenue'] += x.revenue; b['gross_margin'] += x.gross_margin
    b['lost_revenue'] += x.lost_revenue; b['lost_margin'] += x.lost_margin
monthly = []
for row in _scenario_monthly_totals(sl):
    m = row['month']; f = by_month[m]
    monthly.append(dict(month=m, demand=round(row['demand'], 1), produced=round(row['produced'], 1),
        shipped=round(row['shipped'], 1), unmet=round(row['unmet'], 1),
        revenue=round(f['revenue'], 2), gross_margin=round(f['gross_margin'], 2),
        lost_revenue=round(f['lost_revenue'], 2), lost_margin=round(f['lost_margin'], 2)))
gm = fin_mod.gross_margin_by_family(fl); lm = fin_mod.lost_margin_by_family(fl)
recon = []
for f in mut_families:
    fs = [s for s in sl if s.family_id == f.id]; ff = [x for x in fl if x.family_id == f.id]
    td = sum(s.demand_units for s in fs); ts = sum(s.shipped_units for s in fs); tu = sum(s.unmet_units for s in fs)
    dec = next((x for x in ff if x.month == 12), None)
    recon.append(dict(family_id=f.id, demand_units=round(td, 1), shipped_units=round(ts, 1), unmet_units=round(tu, 1),
        fill_rate_pct=round((ts / td * 100) if td else 100, 1), revenue=round(sum(x.revenue for x in ff), 2),
        gross_margin=gm.get(f.id, 0), lost_margin=lm.get(f.id, 0),
        ending_inventory_value=dec.inventory_value if dec else 0))
utilization = {rid: [{'month': ld.month, 'load_hours': ld.load_hours, 'available_hours': ld.available_hours, 'utilization_pct': ld.utilization_pct} for ld in loads if ld.resource_id == rid] for rid in {r.id for r in mut_resources}}
print(json.dumps(dict(summary=summ.__dict__, monthly=monthly, reconciliation=recon, utilization=utilization)))
"""


@unittest.skipUnless(NODE, "node not installed — skipping JS-port golden gate")
class TestJsPortGoldenGate(unittest.TestCase):
    """The JS engine port reproduces the Python engine exactly."""

    def test_identity_0diff(self) -> None:
        proc = _node("_js_identity.js")
        if proc.returncode != 0:
            self.fail(f"identity gate failed:\n{proc.stderr}\n{proc.stdout}")
        self.assertIn("MISMATCHES=0", proc.stdout, proc.stdout)

    def test_representative_lever_mutation_0diff(self) -> None:
        # Python truth: same mutation via the real engine.
        py_mutated = json.loads(_python_run(_PY_MUTATION % str(REPO / "data")))
        tmp = Path(__file__).parent / "_py_mutated.json"
        tmp.write_text(json.dumps(py_mutated))
        try:
            proc = _node("_js_mutation.js", env={"PY_MUTATED": str(tmp)})
        finally:
            tmp.unlink(missing_ok=True)
        if proc.returncode != 0:
            self.fail(f"mutation gate failed:\n{proc.stderr}\n{proc.stdout}")
        self.assertIn("MISMATCHES=0", proc.stdout, proc.stdout)

    def test_pyround_matches_python(self) -> None:
        cases = [(x, dp) for x in _ROUND_CASES for dp in (0, 1, 2, 3)]
        truth_script = (
            "import json\n"
            "cases = " + json.dumps(cases) + "\n"
            "print(json.dumps([round(x, dp) for x, dp in cases]))\n"
        )
        truth = json.loads(_python_run(truth_script))
        proc = _node("_js_pyround.js", env={"TRUTH": json.dumps(truth), "CASES": json.dumps(cases)})
        if proc.returncode != 0:
            self.fail(f"pyRound gate failed:\n{proc.stderr}\n{proc.stdout}")
        self.assertIn("BAD=0", proc.stdout, proc.stdout)


if __name__ == "__main__":
    unittest.main()
