"""Emit mockups/data.js from the real engine — no hand-typed numbers anywhere.

Every figure a mockup renders comes from here, so a reviewer can re-derive it by
running the engine. Regenerate with:

    PYTHONPATH=src python3 mockups/build_data.py

`build_context()` is deliberately not reused: it exposes monthly totals in UNITS
only, and the mockups need monthly revenue and margin too. Those are aggregated
here straight off the per-(family, month) FinanceLines the engine already builds.
"""

from __future__ import annotations

import json
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

from sop_integrated_planning import cli, kpi as kpi_mod
from sop_integrated_planning.dashboard import build_context

REPO = Path(__file__).resolve().parent.parent
MONTH_NAMES = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
               "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]


def main() -> int:
    families, resources = cli._load_or_generate_dataset(REPO / "data")
    loads_by, supply_by, finance_by, summary_by = cli.run_all_scenarios(families, resources)
    kpis = kpi_mod.compute_kpis(resources, loads_by, summary_by, finance_by)
    generated_at = datetime.now(timezone.utc).isoformat()

    ctx = build_context(
        families, resources, loads_by, supply_by, finance_by, summary_by, kpis, generated_at
    )

    payload = {
        "generated_at": generated_at,
        "company": ctx["company"],
        "month_names": MONTH_NAMES,
        "resources": ctx["resources"],
        "families": [
            {k: f[k] for k in ("id", "name", "unit_price", "unit_variable_cost", "unit_margin")}
            for f in ctx["families"]
        ],
        "bottleneck": ctx["bottleneck"],
        "scenarios": {},
    }

    for sid, scen in ctx["scenarios"].items():
        # Monthly revenue / margin / lost margin, summed across families.
        by_month: dict[int, dict[str, float]] = defaultdict(
            lambda: {"revenue": 0.0, "gross_margin": 0.0, "lost_revenue": 0.0, "lost_margin": 0.0}
        )
        for fl in finance_by[sid]:
            bucket = by_month[fl.month]
            bucket["revenue"] += fl.revenue
            bucket["gross_margin"] += fl.gross_margin
            bucket["lost_revenue"] += fl.lost_revenue
            bucket["lost_margin"] += fl.lost_margin

        monthly = []
        for row in scen["monthly_totals"]:
            m = row["month"]
            fin = by_month[m]
            monthly.append({
                "month": m,
                "name": row["month_name"],
                "demand": round(row["demand"], 1),
                "produced": round(row["produced"], 1),
                "shipped": round(row["shipped"], 1),
                "unmet": round(row["unmet"], 1),
                "revenue": round(fin["revenue"], 2),
                "gross_margin": round(fin["gross_margin"], 2),
                "lost_revenue": round(fin["lost_revenue"], 2),
                "lost_margin": round(fin["lost_margin"], 2),
            })

        payload["scenarios"][sid] = {
            "id": sid,
            "summary": scen["summary"],
            "monthly": monthly,
            "utilization": {
                rid: [
                    {"month": r["month"],
                     "load_hours": r["load_hours"],
                     "available_hours": r["available_hours"],
                     "utilization_pct": r["utilization_pct"]}
                    for r in rows
                ]
                for rid, rows in scen["capacity"]["by_resource"].items()
            },
            "reconciliation": scen["reconciliation"],
        }

    out = REPO / "mockups" / "data.js"
    out.write_text(
        "/* GENERATED by mockups/build_data.py — do not hand-edit. */\n"
        "window.SOP_DATA = " + json.dumps(payload, indent=2) + ";\n"
    )
    print(f"Wrote {out} ({out.stat().st_size:,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
