/* GENERATED by mockups/build_data.py — do not hand-edit. */
window.SOP_DATA = {
  "generated_at": "2026-08-12T16:20:39.003115+00:00",
  "company": "Cascade Appliances",
  "month_names": [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec"
  ],
  "resources": [
    {
      "id": "RES-LINEA",
      "name": "Assembly Line A (heavy)",
      "monthly_available_hours": 9500.0
    },
    {
      "id": "RES-LINEB",
      "name": "Assembly Line B (light)",
      "monthly_available_hours": 7800.0
    },
    {
      "id": "RES-QA",
      "name": "Test / QA",
      "monthly_available_hours": 2220.0
    },
    {
      "id": "RES-PKG",
      "name": "Packaging",
      "monthly_available_hours": 1600.0
    }
  ],
  "families": [
    {
      "id": "FAM-REF",
      "name": "Refrigerators",
      "unit_price": 1349.0,
      "unit_variable_cost": 812.0,
      "unit_margin": 537.0
    },
    {
      "id": "FAM-WSH",
      "name": "Washers",
      "unit_price": 799.0,
      "unit_variable_cost": 471.0,
      "unit_margin": 328.0
    },
    {
      "id": "FAM-DRY",
      "name": "Dryers",
      "unit_price": 699.0,
      "unit_variable_cost": 402.0,
      "unit_margin": 297.0
    },
    {
      "id": "FAM-MWV",
      "name": "Microwaves",
      "unit_price": 179.0,
      "unit_variable_cost": 96.0,
      "unit_margin": 83.0
    },
    {
      "id": "FAM-DSH",
      "name": "Dishwashers",
      "unit_price": 649.0,
      "unit_variable_cost": 381.0,
      "unit_margin": 268.0
    },
    {
      "id": "FAM-RNG",
      "name": "Ranges",
      "unit_price": 899.0,
      "unit_variable_cost": 549.0,
      "unit_margin": 350.0
    }
  ],
  "bottleneck": {
    "resource_id": "RES-LINEA",
    "resource_name": "Assembly Line A (heavy)",
    "month": 4,
    "month_name": "Apr",
    "utilization_pct": 114.98
  },
  "scenarios": {
    "base": {
      "id": "base",
      "summary": {
        "scenario": "base",
        "total_revenue": 127687934.9,
        "total_gross_margin": 52203889.6,
        "total_lost_revenue": 0.0,
        "total_lost_margin": 0.0,
        "ending_inventory_value": 8421000.0,
        "fill_rate": 1.0
      },
      "monthly": [
        {
          "month": 1,
          "name": "Jan",
          "demand": 13605.8,
          "produced": 13605.8,
          "shipped": 13605.8,
          "unmet": 0.0,
          "revenue": 9583710.2,
          "gross_margin": 3927084.3,
          "lost_revenue": 0.0,
          "lost_margin": 0.0
        },
        {
          "month": 2,
          "name": "Feb",
          "demand": 12713.8,
          "produced": 12713.8,
          "shipped": 12713.8,
          "unmet": 0.0,
          "revenue": 9021730.2,
          "gross_margin": 3690816.4,
          "lost_revenue": 0.0,
          "lost_margin": 0.0
        },
        {
          "month": 3,
          "name": "Mar",
          "demand": 16007.5,
          "produced": 16007.5,
          "shipped": 16007.5,
          "unmet": 0.0,
          "revenue": 12132811.5,
          "gross_margin": 4951664.3,
          "lost_revenue": 0.0,
          "lost_margin": 0.0
        },
        {
          "month": 4,
          "name": "Apr",
          "demand": 17222.3,
          "produced": 17222.3,
          "shipped": 17222.3,
          "unmet": 0.0,
          "revenue": 13138044.7,
          "gross_margin": 5360203.5,
          "lost_revenue": 0.0,
          "lost_margin": 0.0
        },
        {
          "month": 5,
          "name": "May",
          "demand": 16910.6,
          "produced": 16910.6,
          "shipped": 16910.6,
          "unmet": 0.0,
          "revenue": 12603404.4,
          "gross_margin": 5147697.2,
          "lost_revenue": 0.0,
          "lost_margin": 0.0
        },
        {
          "month": 6,
          "name": "Jun",
          "demand": 14022.0,
          "produced": 14022.0,
          "shipped": 14022.0,
          "unmet": 0.0,
          "revenue": 10117818.0,
          "gross_margin": 4137350.4,
          "lost_revenue": 0.0,
          "lost_margin": 0.0
        },
        {
          "month": 7,
          "name": "Jul",
          "demand": 13233.8,
          "produced": 13233.8,
          "shipped": 13233.8,
          "unmet": 0.0,
          "revenue": 9478629.2,
          "gross_margin": 3875803.5,
          "lost_revenue": 0.0,
          "lost_margin": 0.0
        },
        {
          "month": 8,
          "name": "Aug",
          "demand": 12783.4,
          "produced": 12783.4,
          "shipped": 12783.4,
          "unmet": 0.0,
          "revenue": 8989875.6,
          "gross_margin": 3677728.4,
          "lost_revenue": 0.0,
          "lost_margin": 0.0
        },
        {
          "month": 9,
          "name": "Sep",
          "demand": 12826.5,
          "produced": 12826.5,
          "shipped": 12826.5,
          "unmet": 0.0,
          "revenue": 9062888.5,
          "gross_margin": 3707272.3,
          "lost_revenue": 0.0,
          "lost_margin": 0.0
        },
        {
          "month": 10,
          "name": "Oct",
          "demand": 13636.9,
          "produced": 13636.9,
          "shipped": 13636.9,
          "unmet": 0.0,
          "revenue": 9578599.1,
          "gross_margin": 3916652.4,
          "lost_revenue": 0.0,
          "lost_margin": 0.0
        },
        {
          "month": 11,
          "name": "Nov",
          "demand": 16800.2,
          "produced": 16800.2,
          "shipped": 16800.2,
          "unmet": 0.0,
          "revenue": 11847224.8,
          "gross_margin": 4845475.0,
          "lost_revenue": 0.0,
          "lost_margin": 0.0
        },
        {
          "month": 12,
          "name": "Dec",
          "demand": 17256.3,
          "produced": 17256.3,
          "shipped": 17256.3,
          "unmet": 0.0,
          "revenue": 12133198.7,
          "gross_margin": 4966141.9,
          "lost_revenue": 0.0,
          "lost_margin": 0.0
        }
      ],
      "utilization": {
        "RES-LINEA": [
          {
            "month": 1,
            "load_hours": 6356.93,
            "available_hours": 9500.0,
            "utilization_pct": 66.92
          },
          {
            "month": 2,
            "load_hours": 5783.57,
            "available_hours": 9500.0,
            "utilization_pct": 60.88
          },
          {
            "month": 3,
            "load_hours": 8309.78,
            "available_hours": 9500.0,
            "utilization_pct": 87.47
          },
          {
            "month": 4,
            "load_hours": 8975.96,
            "available_hours": 9500.0,
            "utilization_pct": 94.48
          },
          {
            "month": 5,
            "load_hours": 8485.39,
            "available_hours": 9500.0,
            "utilization_pct": 89.32
          },
          {
            "month": 6,
            "load_hours": 6604.4,
            "available_hours": 9500.0,
            "utilization_pct": 69.52
          },
          {
            "month": 7,
            "load_hours": 6181.04,
            "available_hours": 9500.0,
            "utilization_pct": 65.06
          },
          {
            "month": 8,
            "load_hours": 5692.95,
            "available_hours": 9500.0,
            "utilization_pct": 59.93
          },
          {
            "month": 9,
            "load_hours": 5823.34,
            "available_hours": 9500.0,
            "utilization_pct": 61.3
          },
          {
            "month": 10,
            "load_hours": 5958.25,
            "available_hours": 9500.0,
            "utilization_pct": 62.72
          },
          {
            "month": 11,
            "load_hours": 7591.87,
            "available_hours": 9500.0,
            "utilization_pct": 79.91
          },
          {
            "month": 12,
            "load_hours": 7988.94,
            "available_hours": 9500.0,
            "utilization_pct": 84.09
          }
        ],
        "RES-LINEB": [
          {
            "month": 1,
            "load_hours": 3339.85,
            "available_hours": 7800.0,
            "utilization_pct": 42.82
          },
          {
            "month": 2,
            "load_hours": 3329.06,
            "available_hours": 7800.0,
            "utilization_pct": 42.68
          },
          {
            "month": 3,
            "load_hours": 3805.41,
            "available_hours": 7800.0,
            "utilization_pct": 48.79
          },
          {
            "month": 4,
            "load_hours": 4136.56,
            "available_hours": 7800.0,
            "utilization_pct": 53.03
          },
          {
            "month": 5,
            "load_hours": 4157.61,
            "available_hours": 7800.0,
            "utilization_pct": 53.3
          },
          {
            "month": 6,
            "load_hours": 3614.84,
            "available_hours": 7800.0,
            "utilization_pct": 46.34
          },
          {
            "month": 7,
            "load_hours": 3367.54,
            "available_hours": 7800.0,
            "utilization_pct": 43.17
          },
          {
            "month": 8,
            "load_hours": 3404.23,
            "available_hours": 7800.0,
            "utilization_pct": 43.64
          },
          {
            "month": 9,
            "load_hours": 3330.99,
            "available_hours": 7800.0,
            "utilization_pct": 42.7
          },
          {
            "month": 10,
            "load_hours": 3712.41,
            "available_hours": 7800.0,
            "utilization_pct": 47.59
          },
          {
            "month": 11,
            "load_hours": 4336.76,
            "available_hours": 7800.0,
            "utilization_pct": 55.6
          },
          {
            "month": 12,
            "load_hours": 4238.08,
            "available_hours": 7800.0,
            "utilization_pct": 54.33
          }
        ],
        "RES-QA": [
          {
            "month": 1,
            "load_hours": 1378.61,
            "available_hours": 2220.0,
            "utilization_pct": 62.1
          },
          {
            "month": 2,
            "load_hours": 1289.35,
            "available_hours": 2220.0,
            "utilization_pct": 58.08
          },
          {
            "month": 3,
            "load_hours": 1694.62,
            "available_hours": 2220.0,
            "utilization_pct": 76.33
          },
          {
            "month": 4,
            "load_hours": 1830.64,
            "available_hours": 2220.0,
            "utilization_pct": 82.46
          },
          {
            "month": 5,
            "load_hours": 1772.62,
            "available_hours": 2220.0,
            "utilization_pct": 79.85
          },
          {
            "month": 6,
            "load_hours": 1440.69,
            "available_hours": 2220.0,
            "utilization_pct": 64.9
          },
          {
            "month": 7,
            "load_hours": 1349.11,
            "available_hours": 2220.0,
            "utilization_pct": 60.77
          },
          {
            "month": 8,
            "load_hours": 1288.87,
            "available_hours": 2220.0,
            "utilization_pct": 58.06
          },
          {
            "month": 9,
            "load_hours": 1296.09,
            "available_hours": 2220.0,
            "utilization_pct": 58.38
          },
          {
            "month": 10,
            "load_hours": 1369.65,
            "available_hours": 2220.0,
            "utilization_pct": 61.7
          },
          {
            "month": 11,
            "load_hours": 1689.71,
            "available_hours": 2220.0,
            "utilization_pct": 76.11
          },
          {
            "month": 12,
            "load_hours": 1734.49,
            "available_hours": 2220.0,
            "utilization_pct": 78.13
          }
        ],
        "RES-PKG": [
          {
            "month": 1,
            "load_hours": 946.1,
            "available_hours": 1600.0,
            "utilization_pct": 59.13
          },
          {
            "month": 2,
            "load_hours": 881.32,
            "available_hours": 1600.0,
            "utilization_pct": 55.08
          },
          {
            "month": 3,
            "load_hours": 1155.46,
            "available_hours": 1600.0,
            "utilization_pct": 72.22
          },
          {
            "month": 4,
            "load_hours": 1247.27,
            "available_hours": 1600.0,
            "utilization_pct": 77.95
          },
          {
            "month": 5,
            "load_hours": 1209.17,
            "available_hours": 1600.0,
            "utilization_pct": 75.57
          },
          {
            "month": 6,
            "load_hours": 983.2,
            "available_hours": 1600.0,
            "utilization_pct": 61.45
          },
          {
            "month": 7,
            "load_hours": 922.01,
            "available_hours": 1600.0,
            "utilization_pct": 57.63
          },
          {
            "month": 8,
            "load_hours": 880.02,
            "available_hours": 1600.0,
            "utilization_pct": 55.0
          },
          {
            "month": 9,
            "load_hours": 885.86,
            "available_hours": 1600.0,
            "utilization_pct": 55.37
          },
          {
            "month": 10,
            "load_hours": 934.9,
            "available_hours": 1600.0,
            "utilization_pct": 58.43
          },
          {
            "month": 11,
            "load_hours": 1156.77,
            "available_hours": 1600.0,
            "utilization_pct": 72.3
          },
          {
            "month": 12,
            "load_hours": 1190.48,
            "available_hours": 1600.0,
            "utilization_pct": 74.41
          }
        ]
      },
      "reconciliation": [
        {
          "family_id": "FAM-REF",
          "family_name": "Refrigerators",
          "unit_margin": 537.0,
          "demand_units": 35835.2,
          "shipped_units": 35835.2,
          "unmet_units": 0.0,
          "fill_rate_pct": 100.0,
          "revenue": 48341684.8,
          "gross_margin": 19243502.4,
          "lost_margin": 0.0,
          "ending_inventory_value": 3410400.0
        },
        {
          "family_id": "FAM-WSH",
          "family_name": "Washers",
          "unit_margin": 328.0,
          "demand_units": 29992.5,
          "shipped_units": 29992.5,
          "unmet_units": 0.0,
          "fill_rate_pct": 100.0,
          "revenue": 23964007.5,
          "gross_margin": 9837540.0,
          "lost_margin": 0.0,
          "ending_inventory_value": 1460100.0
        },
        {
          "family_id": "FAM-DRY",
          "family_name": "Dryers",
          "unit_margin": 297.0,
          "demand_units": 23937.4,
          "shipped_units": 23937.4,
          "unmet_units": 0.0,
          "fill_rate_pct": 100.0,
          "revenue": 16732242.6,
          "gross_margin": 7109407.8,
          "lost_margin": 0.0,
          "ending_inventory_value": 1045200.0
        },
        {
          "family_id": "FAM-MWV",
          "family_name": "Microwaves",
          "unit_margin": 83.0,
          "demand_units": 47791.8,
          "shipped_units": 47791.8,
          "unmet_units": 0.0,
          "fill_rate_pct": 100.0,
          "revenue": 8554732.2,
          "gross_margin": 3966719.4,
          "lost_margin": 0.0,
          "ending_inventory_value": 624000.0
        },
        {
          "family_id": "FAM-DSH",
          "family_name": "Dishwashers",
          "unit_margin": 268.0,
          "demand_units": 21525.0,
          "shipped_units": 21525.0,
          "unmet_units": 0.0,
          "fill_rate_pct": 100.0,
          "revenue": 13969725.0,
          "gross_margin": 5768700.0,
          "lost_margin": 0.0,
          "ending_inventory_value": 838200.0
        },
        {
          "family_id": "FAM-RNG",
          "family_name": "Ranges",
          "unit_margin": 350.0,
          "demand_units": 17937.2,
          "shipped_units": 17937.2,
          "unmet_units": 0.0,
          "fill_rate_pct": 100.0,
          "revenue": 16125542.8,
          "gross_margin": 6278020.0,
          "lost_margin": 0.0,
          "ending_inventory_value": 1043100.0
        }
      ]
    },
    "upside": {
      "id": "upside",
      "summary": {
        "scenario": "upside",
        "total_revenue": 148472952.51,
        "total_gross_margin": 60625548.43,
        "total_lost_revenue": 0.0,
        "total_lost_margin": 0.0,
        "ending_inventory_value": 8421000.0,
        "fill_rate": 1.0
      },
      "monthly": [
        {
          "month": 1,
          "name": "Jan",
          "demand": 15183.4,
          "produced": 15183.4,
          "shipped": 15183.4,
          "unmet": 0.0,
          "revenue": 11119288.6,
          "gross_margin": 4550714.58,
          "lost_revenue": 0.0,
          "lost_margin": 0.0
        },
        {
          "month": 2,
          "name": "Feb",
          "demand": 14154.8,
          "produced": 14154.8,
          "shipped": 14154.8,
          "unmet": 0.0,
          "revenue": 10452645.24,
          "gross_margin": 4271052.2,
          "lost_revenue": 0.0,
          "lost_margin": 0.0
        },
        {
          "month": 3,
          "name": "Mar",
          "demand": 18038.1,
          "produced": 18038.1,
          "shipped": 18038.1,
          "unmet": 0.0,
          "revenue": 14195388.87,
          "gross_margin": 5786762.79,
          "lost_revenue": 0.0,
          "lost_margin": 0.0
        },
        {
          "month": 4,
          "name": "Apr",
          "demand": 19417.4,
          "produced": 19417.4,
          "shipped": 19417.4,
          "unmet": 0.0,
          "revenue": 15371443.15,
          "gross_margin": 6264389.12,
          "lost_revenue": 0.0,
          "lost_margin": 0.0
        },
        {
          "month": 5,
          "name": "May",
          "demand": 19000.1,
          "produced": 19000.1,
          "shipped": 19000.1,
          "unmet": 0.0,
          "revenue": 14711840.36,
          "gross_margin": 6001747.17,
          "lost_revenue": 0.0,
          "lost_margin": 0.0
        },
        {
          "month": 6,
          "name": "Jun",
          "demand": 15667.5,
          "produced": 15667.5,
          "shipped": 15667.5,
          "unmet": 0.0,
          "revenue": 11763416.54,
          "gross_margin": 4804250.06,
          "lost_revenue": 0.0,
          "lost_margin": 0.0
        },
        {
          "month": 7,
          "name": "Jul",
          "demand": 14763.1,
          "produced": 14763.1,
          "shipped": 14763.1,
          "unmet": 0.0,
          "revenue": 11015037.45,
          "gross_margin": 4498263.14,
          "lost_revenue": 0.0,
          "lost_margin": 0.0
        },
        {
          "month": 8,
          "name": "Aug",
          "demand": 14207.5,
          "produced": 14207.5,
          "shipped": 14207.5,
          "unmet": 0.0,
          "revenue": 10410099.53,
          "gross_margin": 4253345.65,
          "lost_revenue": 0.0,
          "lost_margin": 0.0
        },
        {
          "month": 9,
          "name": "Sep",
          "demand": 14273.6,
          "produced": 14273.6,
          "shipped": 14273.6,
          "unmet": 0.0,
          "revenue": 10516218.35,
          "gross_margin": 4296047.84,
          "lost_revenue": 0.0,
          "lost_margin": 0.0
        },
        {
          "month": 10,
          "name": "Oct",
          "demand": 15125.5,
          "produced": 15125.5,
          "shipped": 15125.5,
          "unmet": 0.0,
          "revenue": 11065807.48,
          "gross_margin": 4519395.36,
          "lost_revenue": 0.0,
          "lost_margin": 0.0
        },
        {
          "month": 11,
          "name": "Nov",
          "demand": 18673.3,
          "produced": 18673.3,
          "shipped": 18673.3,
          "unmet": 0.0,
          "revenue": 13735052.23,
          "gross_margin": 5610204.52,
          "lost_revenue": 0.0,
          "lost_margin": 0.0
        },
        {
          "month": 12,
          "name": "Dec",
          "demand": 19215.3,
          "produced": 19215.3,
          "shipped": 19215.3,
          "unmet": 0.0,
          "revenue": 14116714.71,
          "gross_margin": 5769376.0,
          "lost_revenue": 0.0,
          "lost_margin": 0.0
        }
      ],
      "utilization": {
        "RES-LINEA": [
          {
            "month": 1,
            "load_hours": 7701.15,
            "available_hours": 9500.0,
            "utilization_pct": 81.06
          },
          {
            "month": 2,
            "load_hours": 7022.98,
            "available_hours": 9500.0,
            "utilization_pct": 73.93
          },
          {
            "month": 3,
            "load_hours": 10111.61,
            "available_hours": 9500.0,
            "utilization_pct": 106.44
          },
          {
            "month": 4,
            "load_hours": 10923.41,
            "available_hours": 9500.0,
            "utilization_pct": 114.98
          },
          {
            "month": 5,
            "load_hours": 10319.08,
            "available_hours": 9500.0,
            "utilization_pct": 108.62
          },
          {
            "month": 6,
            "load_hours": 8027.31,
            "available_hours": 9500.0,
            "utilization_pct": 84.5
          },
          {
            "month": 7,
            "load_hours": 7515.62,
            "available_hours": 9500.0,
            "utilization_pct": 79.11
          },
          {
            "month": 8,
            "load_hours": 6919.31,
            "available_hours": 9500.0,
            "utilization_pct": 72.83
          },
          {
            "month": 9,
            "load_hours": 7081.84,
            "available_hours": 9500.0,
            "utilization_pct": 74.55
          },
          {
            "month": 10,
            "load_hours": 7241.63,
            "available_hours": 9500.0,
            "utilization_pct": 76.23
          },
          {
            "month": 11,
            "load_hours": 9232.11,
            "available_hours": 9500.0,
            "utilization_pct": 97.18
          },
          {
            "month": 12,
            "load_hours": 9719.12,
            "available_hours": 9500.0,
            "utilization_pct": 102.31
          }
        ],
        "RES-LINEB": [
          {
            "month": 1,
            "load_hours": 3482.66,
            "available_hours": 7800.0,
            "utilization_pct": 44.65
          },
          {
            "month": 2,
            "load_hours": 3471.77,
            "available_hours": 7800.0,
            "utilization_pct": 44.51
          },
          {
            "month": 3,
            "load_hours": 3979.21,
            "available_hours": 7800.0,
            "utilization_pct": 51.02
          },
          {
            "month": 4,
            "load_hours": 4328.25,
            "available_hours": 7800.0,
            "utilization_pct": 55.49
          },
          {
            "month": 5,
            "load_hours": 4349.41,
            "available_hours": 7800.0,
            "utilization_pct": 55.76
          },
          {
            "month": 6,
            "load_hours": 3779.35,
            "available_hours": 7800.0,
            "utilization_pct": 48.45
          },
          {
            "month": 7,
            "load_hours": 3511.46,
            "available_hours": 7800.0,
            "utilization_pct": 45.02
          },
          {
            "month": 8,
            "load_hours": 3549.66,
            "available_hours": 7800.0,
            "utilization_pct": 45.51
          },
          {
            "month": 9,
            "load_hours": 3472.5,
            "available_hours": 7800.0,
            "utilization_pct": 44.52
          },
          {
            "month": 10,
            "load_hours": 3864.84,
            "available_hours": 7800.0,
            "utilization_pct": 49.55
          },
          {
            "month": 11,
            "load_hours": 4511.19,
            "available_hours": 7800.0,
            "utilization_pct": 57.84
          },
          {
            "month": 12,
            "load_hours": 4410.29,
            "available_hours": 7800.0,
            "utilization_pct": 56.54
          }
        ],
        "RES-QA": [
          {
            "month": 1,
            "load_hours": 1579.81,
            "available_hours": 2220.0,
            "utilization_pct": 71.16
          },
          {
            "month": 2,
            "load_hours": 1475.0,
            "available_hours": 2220.0,
            "utilization_pct": 66.44
          },
          {
            "month": 3,
            "load_hours": 1958.91,
            "available_hours": 2220.0,
            "utilization_pct": 88.24
          },
          {
            "month": 4,
            "load_hours": 2116.51,
            "available_hours": 2220.0,
            "utilization_pct": 95.34
          },
          {
            "month": 5,
            "load_hours": 2043.76,
            "available_hours": 2220.0,
            "utilization_pct": 92.06
          },
          {
            "month": 6,
            "load_hours": 1653.53,
            "available_hours": 2220.0,
            "utilization_pct": 74.48
          },
          {
            "month": 7,
            "load_hours": 1547.3,
            "available_hours": 2220.0,
            "utilization_pct": 69.7
          },
          {
            "month": 8,
            "load_hours": 1472.96,
            "available_hours": 2220.0,
            "utilization_pct": 66.35
          },
          {
            "month": 9,
            "load_hours": 1483.7,
            "available_hours": 2220.0,
            "utilization_pct": 66.83
          },
          {
            "month": 10,
            "load_hours": 1562.14,
            "available_hours": 2220.0,
            "utilization_pct": 70.37
          },
          {
            "month": 11,
            "load_hours": 1932.68,
            "available_hours": 2220.0,
            "utilization_pct": 87.06
          },
          {
            "month": 12,
            "load_hours": 1989.14,
            "available_hours": 2220.0,
            "utilization_pct": 89.6
          }
        ],
        "RES-PKG": [
          {
            "month": 1,
            "load_hours": 1082.69,
            "available_hours": 1600.0,
            "utilization_pct": 67.67
          },
          {
            "month": 2,
            "load_hours": 1007.0,
            "available_hours": 1600.0,
            "utilization_pct": 62.94
          },
          {
            "month": 3,
            "load_hours": 1334.28,
            "available_hours": 1600.0,
            "utilization_pct": 83.39
          },
          {
            "month": 4,
            "load_hours": 1440.71,
            "available_hours": 1600.0,
            "utilization_pct": 90.04
          },
          {
            "month": 5,
            "load_hours": 1392.64,
            "available_hours": 1600.0,
            "utilization_pct": 87.04
          },
          {
            "month": 6,
            "load_hours": 1127.08,
            "available_hours": 1600.0,
            "utilization_pct": 70.44
          },
          {
            "month": 7,
            "load_hours": 1056.01,
            "available_hours": 1600.0,
            "utilization_pct": 66.0
          },
          {
            "month": 8,
            "load_hours": 1004.36,
            "available_hours": 1600.0,
            "utilization_pct": 62.77
          },
          {
            "month": 9,
            "load_hours": 1012.6,
            "available_hours": 1600.0,
            "utilization_pct": 63.29
          },
          {
            "month": 10,
            "load_hours": 1064.99,
            "available_hours": 1600.0,
            "utilization_pct": 66.56
          },
          {
            "month": 11,
            "load_hours": 1321.15,
            "available_hours": 1600.0,
            "utilization_pct": 82.57
          },
          {
            "month": 12,
            "load_hours": 1362.74,
            "available_hours": 1600.0,
            "utilization_pct": 85.17
          }
        ]
      },
      "reconciliation": [
        {
          "family_id": "FAM-REF",
          "family_name": "Refrigerators",
          "unit_margin": 537.0,
          "demand_units": 44794.0,
          "shipped_units": 44794.0,
          "unmet_units": 0.0,
          "fill_rate_pct": 100.0,
          "revenue": 60427106.0,
          "gross_margin": 24054378.0,
          "lost_margin": 0.0,
          "ending_inventory_value": 3410400.0
        },
        {
          "family_id": "FAM-WSH",
          "family_name": "Washers",
          "unit_margin": 328.0,
          "demand_units": 35991.0,
          "shipped_units": 35991.0,
          "unmet_units": 0.0,
          "fill_rate_pct": 100.0,
          "revenue": 28756809.0,
          "gross_margin": 11805048.0,
          "lost_margin": 0.0,
          "ending_inventory_value": 1460100.0
        },
        {
          "family_id": "FAM-DRY",
          "family_name": "Dryers",
          "unit_margin": 297.0,
          "demand_units": 27528.0,
          "shipped_units": 27528.0,
          "unmet_units": 0.0,
          "fill_rate_pct": 100.0,
          "revenue": 19242065.01,
          "gross_margin": 8175813.03,
          "lost_margin": 0.0,
          "ending_inventory_value": 1045200.0
        },
        {
          "family_id": "FAM-MWV",
          "family_name": "Microwaves",
          "unit_margin": 83.0,
          "demand_units": 47791.8,
          "shipped_units": 47791.8,
          "unmet_units": 0.0,
          "fill_rate_pct": 100.0,
          "revenue": 8554732.2,
          "gross_margin": 3966719.4,
          "lost_margin": 0.0,
          "ending_inventory_value": 624000.0
        },
        {
          "family_id": "FAM-DSH",
          "family_name": "Dishwashers",
          "unit_margin": 268.0,
          "demand_units": 23677.5,
          "shipped_units": 23677.5,
          "unmet_units": 0.0,
          "fill_rate_pct": 100.0,
          "revenue": 15366697.5,
          "gross_margin": 6345570.0,
          "lost_margin": 0.0,
          "ending_inventory_value": 838200.0
        },
        {
          "family_id": "FAM-RNG",
          "family_name": "Ranges",
          "unit_margin": 350.0,
          "demand_units": 17937.2,
          "shipped_units": 17937.2,
          "unmet_units": 0.0,
          "fill_rate_pct": 100.0,
          "revenue": 16125542.8,
          "gross_margin": 6278020.0,
          "lost_margin": 0.0,
          "ending_inventory_value": 1043100.0
        }
      ]
    },
    "constrained": {
      "id": "constrained",
      "summary": {
        "scenario": "constrained",
        "total_revenue": 147221511.84,
        "total_gross_margin": 60093820.42,
        "total_lost_revenue": 1251440.67,
        "total_lost_margin": 531728.01,
        "ending_inventory_value": 7375800.0,
        "fill_rate": 0.9909
      },
      "monthly": [
        {
          "month": 1,
          "name": "Jan",
          "demand": 15183.4,
          "produced": 15183.4,
          "shipped": 15183.4,
          "unmet": 0.0,
          "revenue": 11119288.6,
          "gross_margin": 4550714.58,
          "lost_revenue": 0.0,
          "lost_margin": 0.0
        },
        {
          "month": 2,
          "name": "Feb",
          "demand": 14154.8,
          "produced": 14154.8,
          "shipped": 14154.8,
          "unmet": 0.0,
          "revenue": 10452645.24,
          "gross_margin": 4271052.2,
          "lost_revenue": 0.0,
          "lost_margin": 0.0
        },
        {
          "month": 3,
          "name": "Mar",
          "demand": 18038.1,
          "produced": 17164.4,
          "shipped": 18038.1,
          "unmet": 0.0,
          "revenue": 14195388.87,
          "gross_margin": 5786762.79,
          "lost_revenue": 0.0,
          "lost_margin": 0.0
        },
        {
          "month": 4,
          "name": "Apr",
          "demand": 19417.4,
          "produced": 17383.9,
          "shipped": 19110.2,
          "unmet": 307.2,
          "revenue": 15156724.33,
          "gross_margin": 6173156.66,
          "lost_revenue": 214718.82,
          "lost_margin": 91232.46
        },
        {
          "month": 5,
          "name": "May",
          "demand": 19000.1,
          "produced": 17830.0,
          "shipped": 17830.0,
          "unmet": 1170.1,
          "revenue": 13893933.47,
          "gross_margin": 5654224.5,
          "lost_revenue": 817906.89,
          "lost_margin": 347522.67
        },
        {
          "month": 6,
          "name": "Jun",
          "demand": 15667.5,
          "produced": 15667.5,
          "shipped": 15667.5,
          "unmet": 0.0,
          "revenue": 11763416.54,
          "gross_margin": 4804250.06,
          "lost_revenue": 0.0,
          "lost_margin": 0.0
        },
        {
          "month": 7,
          "name": "Jul",
          "demand": 14763.1,
          "produced": 14763.1,
          "shipped": 14763.1,
          "unmet": 0.0,
          "revenue": 11015037.45,
          "gross_margin": 4498263.14,
          "lost_revenue": 0.0,
          "lost_margin": 0.0
        },
        {
          "month": 8,
          "name": "Aug",
          "demand": 14207.5,
          "produced": 14207.5,
          "shipped": 14207.5,
          "unmet": 0.0,
          "revenue": 10410099.53,
          "gross_margin": 4253345.65,
          "lost_revenue": 0.0,
          "lost_margin": 0.0
        },
        {
          "month": 9,
          "name": "Sep",
          "demand": 14273.6,
          "produced": 14273.6,
          "shipped": 14273.6,
          "unmet": 0.0,
          "revenue": 10516218.35,
          "gross_margin": 4296047.84,
          "lost_revenue": 0.0,
          "lost_margin": 0.0
        },
        {
          "month": 10,
          "name": "Oct",
          "demand": 15125.5,
          "produced": 15125.5,
          "shipped": 15125.5,
          "unmet": 0.0,
          "revenue": 11065807.48,
          "gross_margin": 4519395.36,
          "lost_revenue": 0.0,
          "lost_margin": 0.0
        },
        {
          "month": 11,
          "name": "Nov",
          "demand": 18673.3,
          "produced": 18673.3,
          "shipped": 18673.3,
          "unmet": 0.0,
          "revenue": 13735052.23,
          "gross_margin": 5610204.52,
          "lost_revenue": 0.0,
          "lost_margin": 0.0
        },
        {
          "month": 12,
          "name": "Dec",
          "demand": 19215.3,
          "produced": 18902.2,
          "shipped": 18902.2,
          "unmet": 313.0,
          "revenue": 13897899.75,
          "gross_margin": 5676403.12,
          "lost_revenue": 218814.96,
          "lost_margin": 92972.88
        }
      ],
      "utilization": {
        "RES-LINEA": [
          {
            "month": 1,
            "load_hours": 7701.15,
            "available_hours": 9500.0,
            "utilization_pct": 81.06
          },
          {
            "month": 2,
            "load_hours": 7022.98,
            "available_hours": 9500.0,
            "utilization_pct": 73.93
          },
          {
            "month": 3,
            "load_hours": 10111.61,
            "available_hours": 9500.0,
            "utilization_pct": 106.44
          },
          {
            "month": 4,
            "load_hours": 10923.41,
            "available_hours": 9500.0,
            "utilization_pct": 114.98
          },
          {
            "month": 5,
            "load_hours": 10319.08,
            "available_hours": 9500.0,
            "utilization_pct": 108.62
          },
          {
            "month": 6,
            "load_hours": 8027.31,
            "available_hours": 9500.0,
            "utilization_pct": 84.5
          },
          {
            "month": 7,
            "load_hours": 7515.62,
            "available_hours": 9500.0,
            "utilization_pct": 79.11
          },
          {
            "month": 8,
            "load_hours": 6919.31,
            "available_hours": 9500.0,
            "utilization_pct": 72.83
          },
          {
            "month": 9,
            "load_hours": 7081.84,
            "available_hours": 9500.0,
            "utilization_pct": 74.55
          },
          {
            "month": 10,
            "load_hours": 7241.63,
            "available_hours": 9500.0,
            "utilization_pct": 76.23
          },
          {
            "month": 11,
            "load_hours": 9232.11,
            "available_hours": 9500.0,
            "utilization_pct": 97.18
          },
          {
            "month": 12,
            "load_hours": 9719.12,
            "available_hours": 9500.0,
            "utilization_pct": 102.31
          }
        ],
        "RES-LINEB": [
          {
            "month": 1,
            "load_hours": 3482.66,
            "available_hours": 7800.0,
            "utilization_pct": 44.65
          },
          {
            "month": 2,
            "load_hours": 3471.77,
            "available_hours": 7800.0,
            "utilization_pct": 44.51
          },
          {
            "month": 3,
            "load_hours": 3979.21,
            "available_hours": 7800.0,
            "utilization_pct": 51.02
          },
          {
            "month": 4,
            "load_hours": 4328.25,
            "available_hours": 7800.0,
            "utilization_pct": 55.49
          },
          {
            "month": 5,
            "load_hours": 4349.41,
            "available_hours": 7800.0,
            "utilization_pct": 55.76
          },
          {
            "month": 6,
            "load_hours": 3779.35,
            "available_hours": 7800.0,
            "utilization_pct": 48.45
          },
          {
            "month": 7,
            "load_hours": 3511.46,
            "available_hours": 7800.0,
            "utilization_pct": 45.02
          },
          {
            "month": 8,
            "load_hours": 3549.66,
            "available_hours": 7800.0,
            "utilization_pct": 45.51
          },
          {
            "month": 9,
            "load_hours": 3472.5,
            "available_hours": 7800.0,
            "utilization_pct": 44.52
          },
          {
            "month": 10,
            "load_hours": 3864.84,
            "available_hours": 7800.0,
            "utilization_pct": 49.55
          },
          {
            "month": 11,
            "load_hours": 4511.19,
            "available_hours": 7800.0,
            "utilization_pct": 57.84
          },
          {
            "month": 12,
            "load_hours": 4410.29,
            "available_hours": 7800.0,
            "utilization_pct": 56.54
          }
        ],
        "RES-QA": [
          {
            "month": 1,
            "load_hours": 1579.81,
            "available_hours": 2220.0,
            "utilization_pct": 71.16
          },
          {
            "month": 2,
            "load_hours": 1475.0,
            "available_hours": 2220.0,
            "utilization_pct": 66.44
          },
          {
            "month": 3,
            "load_hours": 1958.91,
            "available_hours": 2220.0,
            "utilization_pct": 88.24
          },
          {
            "month": 4,
            "load_hours": 2116.51,
            "available_hours": 2220.0,
            "utilization_pct": 95.34
          },
          {
            "month": 5,
            "load_hours": 2043.76,
            "available_hours": 2220.0,
            "utilization_pct": 92.06
          },
          {
            "month": 6,
            "load_hours": 1653.53,
            "available_hours": 2220.0,
            "utilization_pct": 74.48
          },
          {
            "month": 7,
            "load_hours": 1547.3,
            "available_hours": 2220.0,
            "utilization_pct": 69.7
          },
          {
            "month": 8,
            "load_hours": 1472.96,
            "available_hours": 2220.0,
            "utilization_pct": 66.35
          },
          {
            "month": 9,
            "load_hours": 1483.7,
            "available_hours": 2220.0,
            "utilization_pct": 66.83
          },
          {
            "month": 10,
            "load_hours": 1562.14,
            "available_hours": 2220.0,
            "utilization_pct": 70.37
          },
          {
            "month": 11,
            "load_hours": 1932.68,
            "available_hours": 2220.0,
            "utilization_pct": 87.06
          },
          {
            "month": 12,
            "load_hours": 1989.14,
            "available_hours": 2220.0,
            "utilization_pct": 89.6
          }
        ],
        "RES-PKG": [
          {
            "month": 1,
            "load_hours": 1082.69,
            "available_hours": 1600.0,
            "utilization_pct": 67.67
          },
          {
            "month": 2,
            "load_hours": 1007.0,
            "available_hours": 1600.0,
            "utilization_pct": 62.94
          },
          {
            "month": 3,
            "load_hours": 1334.28,
            "available_hours": 1600.0,
            "utilization_pct": 83.39
          },
          {
            "month": 4,
            "load_hours": 1440.71,
            "available_hours": 1600.0,
            "utilization_pct": 90.04
          },
          {
            "month": 5,
            "load_hours": 1392.64,
            "available_hours": 1600.0,
            "utilization_pct": 87.04
          },
          {
            "month": 6,
            "load_hours": 1127.08,
            "available_hours": 1600.0,
            "utilization_pct": 70.44
          },
          {
            "month": 7,
            "load_hours": 1056.01,
            "available_hours": 1600.0,
            "utilization_pct": 66.0
          },
          {
            "month": 8,
            "load_hours": 1004.36,
            "available_hours": 1600.0,
            "utilization_pct": 62.77
          },
          {
            "month": 9,
            "load_hours": 1012.6,
            "available_hours": 1600.0,
            "utilization_pct": 63.29
          },
          {
            "month": 10,
            "load_hours": 1064.99,
            "available_hours": 1600.0,
            "utilization_pct": 66.56
          },
          {
            "month": 11,
            "load_hours": 1321.15,
            "available_hours": 1600.0,
            "utilization_pct": 82.57
          },
          {
            "month": 12,
            "load_hours": 1362.74,
            "available_hours": 1600.0,
            "utilization_pct": 85.17
          }
        ]
      },
      "reconciliation": [
        {
          "family_id": "FAM-REF",
          "family_name": "Refrigerators",
          "unit_margin": 537.0,
          "demand_units": 44794.0,
          "shipped_units": 44794.0,
          "unmet_units": 0.0,
          "fill_rate_pct": 100.0,
          "revenue": 60427106.0,
          "gross_margin": 24054378.0,
          "lost_margin": 0.0,
          "ending_inventory_value": 3410400.0
        },
        {
          "family_id": "FAM-WSH",
          "family_name": "Washers",
          "unit_margin": 328.0,
          "demand_units": 35991.0,
          "shipped_units": 35991.0,
          "unmet_units": 0.0,
          "fill_rate_pct": 100.0,
          "revenue": 28756809.0,
          "gross_margin": 11805048.0,
          "lost_margin": 0.0,
          "ending_inventory_value": 1460100.0
        },
        {
          "family_id": "FAM-DRY",
          "family_name": "Dryers",
          "unit_margin": 297.0,
          "demand_units": 27528.0,
          "shipped_units": 25737.7,
          "unmet_units": 1790.3,
          "fill_rate_pct": 93.5,
          "revenue": 17990624.34,
          "gross_margin": 7644085.02,
          "lost_margin": 531728.01,
          "ending_inventory_value": 0.0
        },
        {
          "family_id": "FAM-MWV",
          "family_name": "Microwaves",
          "unit_margin": 83.0,
          "demand_units": 47791.8,
          "shipped_units": 47791.8,
          "unmet_units": 0.0,
          "fill_rate_pct": 100.0,
          "revenue": 8554732.2,
          "gross_margin": 3966719.4,
          "lost_margin": 0.0,
          "ending_inventory_value": 624000.0
        },
        {
          "family_id": "FAM-DSH",
          "family_name": "Dishwashers",
          "unit_margin": 268.0,
          "demand_units": 23677.5,
          "shipped_units": 23677.5,
          "unmet_units": 0.0,
          "fill_rate_pct": 100.0,
          "revenue": 15366697.5,
          "gross_margin": 6345570.0,
          "lost_margin": 0.0,
          "ending_inventory_value": 838200.0
        },
        {
          "family_id": "FAM-RNG",
          "family_name": "Ranges",
          "unit_margin": 350.0,
          "demand_units": 17937.2,
          "shipped_units": 17937.2,
          "unmet_units": 0.0,
          "fill_rate_pct": 100.0,
          "revenue": 16125542.8,
          "gross_margin": 6278020.0,
          "lost_margin": 0.0,
          "ending_inventory_value": 1043100.0
        }
      ]
    }
  }
};
