/*
 * engine-port.js — a faithful JS port of the S&OP engine's arithmetic.
 *
 * Mirrors src/sop_integrated_planning/{demand,capacity,constrain,finance}.py
 * so that a lever drag can recompute a scenario entirely client-side
 * (SCOPE §2 row 7) with NO Python round-trip. The one thing this port is
 * for is reproducing the Python engine byte-for-byte for the identity
 * lever set: the golden-fixture test (tests/test_js_port.py) asserts
 * 0-diff against mockups/data.js, which is generated by the real engine.
 *
 * This file is dual-use: it loads in the browser (the dashboard's app
 * script sets window.LEVER_ENGINE from the module body) AND under Node
 * (module.exports) for the golden-fixture harness. It must therefore
 * reference no DOM, no window/document at load time.
 *
 * The two deliberate decisions this port encodes, with reasons:
 *  1. Rationing sorts by RAW unit_margin, not by contribution-per-
 *     bottleneck-hour. SCOPE §8b #1 says the engine SHOULD sort by the
 *     latter, but the shipped engine and the golden fixture encode the
 *     former. The port must match the fixture, or 0-diff is unreachable.
 *     The §8b correction is a separate engine change with its own test.
 *  2. Rounding is Python's banker's rounding (ties-to-even on the decimal
 *     expansion), NOT JS Math.round (ties-away on the binary float).
 *     pyRound() below reproduces Python exactly; without it the golden
 *     gate fails on real data (e.g. 3008.125, 2007.7849999999999).
 *
 * The engine input is D (the embedded const DATA) mutated by lever
 * overrides — levers alter D.families / D.resources (canonical inputs),
 * never D.scenarios (precomputed outputs). "custom" is a scenario key on
 * the JS side only; Python never emits it.
 */
(function (root, factory) {
  var mod = factory();
  if (typeof module !== "undefined" && module.exports) {
    module.exports = mod;                 // Node: golden-fixture harness
  }
  if (root) {
    root.LEVER_ENGINE = mod;              // Browser: dashboard app script
  }
})(typeof self !== "undefined" ? self : typeof globalThis !== "undefined" ? globalThis : null, function () {
  "use strict";

  var MONTHS = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12];
  // custom defaults to CONSTRAINED semantics: per-family upside uplift IS
  // applied (the lever scenario starts from the same demand as the shipped
  // constrained plan), capacity is held at installed hours, and rationing is
  // by unit margin unless the user changes the rule. It is NOT the base
  // plan. This keeps "custom with no levers moved" == the constrained
  // scenario, which is what the dashboard shows on first render.
  var UPLIFT_SCENARIOS = { upside: true, constrained: true, custom: true };
  var EPS = 1e-9;

  /* ---- Python-compatible banker's rounding --------------------------------
     Python round(x, dp) rounds ties to even on the DECIMAL expansion; JS
     Math.round(x*10^dp)/10^dp rounds ties away on the BINARY float. These
     diverge on real data. Strategy: get the number's full decimal
     representation via toFixed(20), walk the significant digits, decide the
     tie, then round-half-to-even. */
  function pyRound(x, dp) {
    if (dp === undefined) dp = 0;
    if (x === Infinity || x === -Infinity) return x;
    if (x !== x) return x;                       // NaN
    var neg = x < 0 || (x === 0 && 1 / x < 0);
    var s = Math.abs(x).toFixed(20);
    // integer part and fraction digits
    var dot = s.indexOf(".");
    var ip = s.slice(0, dot);
    var frac = s.slice(dot + 1);
    // strip trailing zeros
    var f = frac.replace(/0+$/, "");
    // we need digit at position dp+1 (1-based) to decide, and all after it
    if (dp < 0) {
      // rounding to an integer multiple of 10^(-dp)
      dp = 0;
    }
    var digits = (ip + f);                        // significant decimal digits
    var intVal = parseInt(ip, 10);
    if (digits.length <= dp) {
      // not enough fractional digits to matter; value is already exact
      return neg ? -Number(ip + "." + f) : Number(ip + "." + f);
    }
    var factor = Math.pow(10, dp);
    // Treat the value as a fixed-point number with `dp` decimals: integer
    // part stays integer, fraction contributes dp digits (zero-padded).
    var keep = ip.length + dp;                       // digits needed for the scaled value
    var scaled = (ip + f) || "0";
    // zero-pad right so slice(0, keep) always has `keep` digits
    while (scaled.length < keep) scaled += "0";
    var head = scaled.slice(0, keep);                // integer part of scaled value
    var tail = scaled.slice(keep);                   // the rest decides rounding
    var headVal = parseInt(head || "0", 10);
    var tailVal = tail.length ? parseInt(tail, 10) : 0;
    var firstTail = tail.length ? parseInt(tail[0], 10) : 0;
    var roundUp = false;
    if (tailVal > 0) {
      if (firstTail > 5) roundUp = true;
      else if (firstTail === 5) {
        var rest = tail.slice(1);
        var restVal = rest.length ? parseInt(rest, 10) : 0;
        if (restVal > 0) roundUp = true;
        else roundUp = (headVal % 2 === 1);          // exact tie: round to even
      }
      if (roundUp) headVal += 1;
    }
    var out = headVal / factor;
    return neg ? -out : out;
  }

  /* ---- demand.py ---------------------------------------------------------*/
  function demandUnits(family, month, tag) {
    var base = family.base_monthly_demand[month - 1];
    if (UPLIFT_SCENARIOS[tag]) {
      return pyRound(base * (1 + family.upside_uplift_pct), 2);
    }
    return base;
  }

  /* ---- capacity.py compute_loads ------------------------------------------*/
  function computeLoads(families, resources, tag, demandByFm) {
    var loads = [];
    resources.forEach(function (resource) {
      MONTHS.forEach(function (month) {
        var loadHours = 0;
        families.forEach(function (family) {
          var hpu = (family.resource_hours_per_unit[resource.id] || 0);
          if (hpu <= 0) return;
          var demand = demandByFm[family.id + "|" + month] || 0;
          loadHours += demand * hpu;
        });
        loadHours = pyRound(loadHours, 2);
        var utilization = resource.monthly_available_hours
          ? (loadHours / resource.monthly_available_hours * 100.0)
          : 0.0;
        loads.push({
          scenario: tag,
          resource_id: resource.id,
          month: month,
          load_hours: loadHours,
          available_hours: resource.monthly_available_hours,
          utilization_pct: pyRound(utilization, 2),
          is_bottleneck: utilization > 100.0,
        });
      });
    });
    return loads;
  }

  function loadHoursByResourceMonth(loads) {
    var map = {};
    loads.forEach(function (ld) {
      map[ld.resource_id + "|" + ld.month] = ld.load_hours;
    });
    return map;
  }

  function loadLookup(loads) {
    var map = {};
    loads.forEach(function (ld) {
      map[ld.resource_id + "|" + ld.month] = ld;
    });
    return map;
  }

  /* ---- constrain.py effective_capacity_hours ------------------------------*/
  function effectiveCapacity(tag, resource, loadHours) {
    if (tag === "upside") return Math.max(resource.monthly_available_hours, loadHours);
    return resource.monthly_available_hours;
  }

  /* ---- constrain.py _allowed_units_this_month ------------------------------
     rationRule: "throughput-per-constraint" (default, matches Python) |
                 "fair-share" (new) | "strategic-priority" (new).            */
  function allowedUnitsThisMonth(month, families, resources, demandByFm, loadByRm, tag, rationRule) {
    var allowed = {};
    resources.forEach(function (resource) {
      var users = families.filter(function (f) {
        return (f.resource_hours_per_unit[resource.id] || 0) > 0;
      });
      if (!users.length) return;
      var loadHours = loadByRm[resource.id + "|" + month] || 0;
      var capacityHours = effectiveCapacity(tag, resource, loadHours);

      if (loadHours <= capacityHours + EPS) {
        users.forEach(function (family) {
          allowed[family.id + "|" + resource.id] = demandByFm[family.id + "|" + month] || 0;
        });
        return;
      }

      // ration: order by the chosen rule. Fair-share allocates proportionally
      // to each user's demand (an equal service ratio); the others are greedy
      // priority fills.
      if (rationRule === "fair-share") {
        var totalAsk = 0;
        users.forEach(function (u) {
          totalAsk += (demandByFm[u.id + "|" + month] || 0) * u.resource_hours_per_unit[resource.id];
        });
        var ratio = totalAsk > 0 ? capacityHours / totalAsk : 0;
        users.forEach(function (u) {
          var want = (demandByFm[u.id + "|" + month] || 0) * u.resource_hours_per_unit[resource.id];
          var granted = Math.min(want, want * ratio);
          allowed[u.id + "|" + resource.id] = u.resource_hours_per_unit[resource.id] > 0
            ? granted / u.resource_hours_per_unit[resource.id] : (demandByFm[u.id + "|" + month] || 0);
        });
        return;
      }

      var ordered = users.slice();
      if (rationRule === "strategic-priority") {
        // honest "priority" = unit-margin tiers (documented); higher margin first
        ordered.sort(function (a, b) { return b.unit_margin - a.unit_margin; });
      } else {
        // throughput-per-constraint — descending unit_margin (matches Python)
        ordered.sort(function (a, b) { return b.unit_margin - a.unit_margin; });
      }

      var remaining = capacityHours;
      ordered.forEach(function (family) {
        var hpu = family.resource_hours_per_unit[resource.id];
        var demand = demandByFm[family.id + "|" + month] || 0;
        var wanted = demand * hpu;
        var granted = Math.max(0, Math.min(wanted, remaining));
        allowed[family.id + "|" + resource.id] = hpu > 0 ? granted / hpu : demand;
        remaining = Math.max(0, remaining - granted);
      });
    });
    return allowed;
  }

  /* ---- constrain.py build_supply_plan -------------------------------------*/
  function buildSupplyPlan(families, resources, tag, rationRule) {
    var demandByFm = {};
    families.forEach(function (f) {
      MONTHS.forEach(function (m) {
        demandByFm[f.id + "|" + m] = demandUnits(f, m, tag);
      });
    });
    var loads = computeLoads(families, resources, tag, demandByFm);
    var loadByRm = loadHoursByResourceMonth(loads);

    var opening = {};
    families.forEach(function (f) { opening[f.id] = f.opening_inventory_units; });
    var lines = [];

    MONTHS.forEach(function (month) {
      var allowed = allowedUnitsThisMonth(month, families, resources, demandByFm, loadByRm, tag, rationRule);
      families.forEach(function (family) {
        var demand = demandByFm[family.id + "|" + month] || 0;
        var usedResources = Object.keys(family.resource_hours_per_unit).filter(function (rid) {
          return family.resource_hours_per_unit[rid] > 0;
        });
        var produced;
        if (usedResources.length) {
          produced = Math.min.apply(null, usedResources.map(function (rid) {
            return allowed[family.id + "|" + rid];
          }));
        } else {
          produced = demand;
        }
        // no build-ahead: never produce more than the month's own demand
        produced = Math.max(0, Math.min(produced, demand));

        var openingUnits = opening[family.id];
        var shipped = Math.min(openingUnits + produced, demand);
        var unmet = Math.max(0, demand - shipped);
        var ending = Math.max(0, openingUnits + produced - shipped);
        var fillRate = demand > 0 ? shipped / demand : 1.0;

        lines.push({
          scenario: tag,
          family_id: family.id,
          month: month,
          demand_units: pyRound(demand, 2),
          produced_units: pyRound(produced, 2),
          opening_inventory_units: pyRound(openingUnits, 2),
          shipped_units: pyRound(shipped, 2),
          unmet_units: pyRound(unmet, 2),
          ending_inventory_units: pyRound(ending, 2),
          fill_rate: pyRound(fillRate, 4),
        });
        opening[family.id] = ending;   // RAW, unrounded — matches constrain.py:144
      });
    });

    return { lines: lines, loads: loads };
  }

  /* ---- finance.py ----------------------------------------------------------*/
  function buildFinance(supplyLines, families) {
    var byId = {};
    families.forEach(function (f) { byId[f.id] = f; });
    return supplyLines.map(function (sl) {
      var family = byId[sl.family_id];
      return {
        scenario: sl.scenario,
        family_id: sl.family_id,
        month: sl.month,
        revenue: pyRound(sl.shipped_units * family.unit_price, 2),
        gross_margin: pyRound(sl.shipped_units * family.unit_margin, 2),
        lost_revenue: pyRound(sl.unmet_units * family.unit_price, 2),
        lost_margin: pyRound(sl.unmet_units * family.unit_margin, 2),
        inventory_value: pyRound(sl.ending_inventory_units * family.unit_variable_cost, 2),
      };
    });
  }

  function summarize(tag, supplyLines, financeLines) {
    var totalDemand = 0, totalShipped = 0;
    supplyLines.forEach(function (sl) {
      totalDemand += sl.demand_units;
      totalShipped += sl.shipped_units;
    });
    var fill = totalDemand > 0 ? totalShipped / totalDemand : 1.0;
    // ending inventory value = December only (point-in-time balance)
    var decValue = 0;
    financeLines.forEach(function (fl) {
      if (fl.month === 12) decValue += fl.inventory_value;
    });
    var totalRev = 0, totalGM = 0, totalLostRev = 0, totalLostM = 0;
    financeLines.forEach(function (fl) {
      totalRev += fl.revenue;
      totalGM += fl.gross_margin;
      totalLostRev += fl.lost_revenue;
      totalLostM += fl.lost_margin;
    });
    return {
      scenario: tag,
      total_revenue: pyRound(totalRev, 2),
      total_gross_margin: pyRound(totalGM, 2),
      total_lost_revenue: pyRound(totalLostRev, 2),
      total_lost_margin: pyRound(totalLostM, 2),
      ending_inventory_value: pyRound(decValue, 2),
      fill_rate: pyRound(fill, 4),
    };
  }

  function grossMarginByFamily(financeLines) {
    var m = {};
    financeLines.forEach(function (fl) {
      m[fl.family_id] = (m[fl.family_id] || 0) + fl.gross_margin;
    });
    var out = {};
    Object.keys(m).forEach(function (k) { out[k] = pyRound(m[k], 2); });
    return out;
  }

  function lostMarginByFamily(financeLines) {
    var m = {};
    financeLines.forEach(function (fl) {
      m[fl.family_id] = (m[fl.family_id] || 0) + fl.lost_margin;
    });
    var out = {};
    Object.keys(m).forEach(function (k) { out[k] = pyRound(m[k], 2); });
    return out;
  }

  /* ---- dashboard.py _scenario_monthly_totals + finance merge ----------------*/
  function buildMonthly(supplyLines, financeLines) {
    var totals = {};
    MONTHS.forEach(function (m) { totals[m] = { demand: 0, produced: 0, shipped: 0, unmet: 0 }; });
    supplyLines.forEach(function (sl) {
      var t = totals[sl.month];
      t.demand += sl.demand_units;
      t.produced += sl.produced_units;
      t.shipped += sl.shipped_units;
      t.unmet += sl.unmet_units;
    });
    var byMonthFin = {};
    financeLines.forEach(function (fl) {
      var b = byMonthFin[fl.month] = byMonthFin[fl.month] || { revenue: 0, gross_margin: 0, lost_revenue: 0, lost_margin: 0 };
      b.revenue += fl.revenue;
      b.gross_margin += fl.gross_margin;
      b.lost_revenue += fl.lost_revenue;
      b.lost_margin += fl.lost_margin;
    });
    return MONTHS.map(function (m) {
      var f = byMonthFin[m] || { revenue: 0, gross_margin: 0, lost_revenue: 0, lost_margin: 0 };
      return {
        month: m,
        name: MONTH_NAMES[m - 1],
        demand: pyRound(totals[m].demand, 1),
        produced: pyRound(totals[m].produced, 1),
        shipped: pyRound(totals[m].shipped, 1),
        unmet: pyRound(totals[m].unmet, 1),
        revenue: pyRound(f.revenue, 2),
        gross_margin: pyRound(f.gross_margin, 2),
        lost_revenue: pyRound(f.lost_revenue, 2),
        lost_margin: pyRound(f.lost_margin, 2),
      };
    });
  }

  var MONTH_NAMES = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
                     "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

  /* ---- dashboard.py _family_reconciliation_rows -----------------------------*/
  function buildReconciliation(families, supplyLines, financeLines) {
    var gmByFam = grossMarginByFamily(financeLines);
    var lmByFam = lostMarginByFamily(financeLines);
    return families.map(function (family) {
      var famSupply = supplyLines.filter(function (s) { return s.family_id === family.id; });
      var famFinance = financeLines.filter(function (f) { return f.family_id === family.id; });
      var totalDemand = 0, totalShipped = 0, totalUnmet = 0;
      famSupply.forEach(function (s) {
        totalDemand += s.demand_units;
        totalShipped += s.shipped_units;
        totalUnmet += s.unmet_units;
      });
      var december = null;
      famFinance.forEach(function (f) { if (f.month === 12) december = f; });
      var fillRate = totalDemand > 0 ? (totalShipped / totalDemand * 100.0) : 100.0;
      return {
        family_id: family.id,
        family_name: family.name,
        unit_margin: family.unit_margin,
        demand_units: pyRound(totalDemand, 1),
        shipped_units: pyRound(totalShipped, 1),
        unmet_units: pyRound(totalUnmet, 1),
        fill_rate_pct: pyRound(fillRate, 1),
        revenue: pyRound(famFinance.reduce(function (a, f) { return a + f.revenue; }, 0), 2),
        gross_margin: gmByFam[family.id] || 0.0,
        lost_margin: lmByFam[family.id] || 0.0,
        ending_inventory_value: december ? december.inventory_value : 0.0,
      };
    });
  }

  /* ---- dashboard.py _provenance ---------------------------------------------*/
  function buildProvenance(tag, families, resources, demandByFm, loadByRm, loads, supplyLines, financeLines) {
    var resById = {};
    resources.forEach(function (r) { resById[r.id] = r; });
    var loadLk = loadLookup(loads);
    var supplyLk = {};
    supplyLines.forEach(function (sl) { supplyLk[sl.family_id + "|" + sl.month] = sl; });
    var financeLk = {};
    financeLines.forEach(function (fl) { financeLk[fl.family_id + "|" + fl.month] = fl; });
    var allowedByMonth = {};
    MONTHS.forEach(function (m) {
      allowedByMonth[m] = allowedUnitsThisMonth(m, families, resources, demandByFm, loadByRm, tag, "throughput-per-constraint");
    });

    var out = {};
    families.forEach(function (family) {
      var resourceIds = Object.keys(family.resource_hours_per_unit).filter(function (rid) {
        return family.resource_hours_per_unit[rid] > 0;
      });
      var monthsOut = {};
      MONTHS.forEach(function (month) {
        var demandUnitsV = demandByFm[family.id + "|" + month] || 0;
        var upliftApplied = UPLIFT_SCENARIOS[tag];
        var allowed = allowedByMonth[month];

        var capacityRows = [], rationingRows = [];
        resourceIds.forEach(function (rid) {
          var resource = resById[rid];
          var ld = loadLk[rid + "|" + month];
          var hpu = family.resource_hours_per_unit[rid];
          capacityRows.push({
            resource_id: rid,
            load_hours: ld.load_hours,
            available_hours: ld.available_hours,
            utilization_pct: ld.utilization_pct,
            is_bottleneck: ld.is_bottleneck,
            hours_per_unit: hpu,
          });

          var effHours = effectiveCapacity(tag, resource, ld.load_hours);
          var constrained = ld.load_hours > effHours + EPS;
          var users = families.filter(function (f) { return (f.resource_hours_per_unit[rid] || 0) > 0; })
            .sort(function (a, b) { return b.unit_margin - a.unit_margin; });
          var cumulative = 0;
          var row = null;
          users.forEach(function (u, i) {
            var uAllowedUnits = allowed[u.id + "|" + rid];
            var uGrantedHours = uAllowedUnits * u.resource_hours_per_unit[rid];
            if (u.id === family.id) {
              var wanted = (demandByFm[u.id + "|" + month] || 0) * u.resource_hours_per_unit[rid];
              var remainingBefore = Math.max(0, effHours - cumulative);
              var remainingAfter = Math.max(0, remainingBefore - uGrantedHours);
              row = {
                resource_id: rid,
                constrained: constrained,
                rank: i + 1,
                n_users: users.length,
                unit_margin: pyRound(u.unit_margin, 2),
                wanted_hours: pyRound(wanted, 2),
                remaining_before_hours: pyRound(remainingBefore, 2),
                granted_hours: pyRound(uGrantedHours, 2),
                remaining_after_hours: pyRound(remainingAfter, 2),
                allowed_units: pyRound(uAllowedUnits, 2),
              };
            }
            cumulative += uGrantedHours;
          });
          rationingRows.push(row);
        });

        var sl = supplyLk[family.id + "|" + month];
        var fl = financeLk[family.id + "|" + month];
        monthsOut[String(month)] = {
          demand: {
            base_units: family.base_monthly_demand[month - 1],
            uplift_pct: upliftApplied ? family.upside_uplift_pct : 0.0,
            uplift_applied: upliftApplied,
            demand_units: pyRound(demandUnitsV, 2),
          },
          capacity: capacityRows,
          rationing: rationingRows,
          supply: sl,
          financials: {
            scenario: fl.scenario,
            family_id: fl.family_id,
            month: fl.month,
            revenue: fl.revenue,
            gross_margin: fl.gross_margin,
            lost_revenue: fl.lost_revenue,
            lost_margin: fl.lost_margin,
            inventory_value: fl.inventory_value,
            unit_price: family.unit_price,
            unit_variable_cost: family.unit_variable_cost,
            unit_margin: family.unit_margin,
          },
        };
      });
      out[family.id] = monthsOut;
    });
    return out;
  }

  /* ---- applyLevers: mutate D.families / D.resources -------------------------*/
  function applyLevers(D, levers) {
    levers = levers || {};
    var families = D.families.map(function (f) {
      var fam = Object.assign({}, f, { resource_hours_per_unit: Object.assign({}, f.resource_hours_per_unit) });
      var base = fam.base_monthly_demand.slice();
      // seasonality shift (± months): circular rotate of base_monthly_demand
      var shift = levers.seasonShift || 0;
      if (shift !== 0) {
        var n = ((shift % 12) + 12) % 12;
        base = base.slice(12 - n).concat(base.slice(0, 12 - n));
      }
      var volMult = (levers.volMult || 0) / 100;
      fam.base_monthly_demand = base.map(function (v) { return v * (1 + volMult); });
      if (levers.familyUplift && levers.familyUplift[f.id] !== undefined) {
        fam.upside_uplift_pct = levers.familyUplift[f.id] / 100;
      }
      if (levers.priceDeltaPct && levers.priceDeltaPct[f.id] !== undefined) {
        fam.unit_price = fam.unit_price * (1 + levers.priceDeltaPct[f.id] / 100);
      }
      if (levers.vcDeltaPct && levers.vcDeltaPct[f.id] !== undefined) {
        fam.unit_variable_cost = fam.unit_variable_cost * (1 + levers.vcDeltaPct[f.id] / 100);
      }
      // unit_margin must be recomputed (not stale) — it's the rationing sort key
      fam.unit_margin = pyRound(fam.unit_price - fam.unit_variable_cost, 4);
      if (levers.openingDeltaPct && levers.openingDeltaPct[f.id] !== undefined) {
        fam.opening_inventory_units = fam.opening_inventory_units * (1 + levers.openingDeltaPct[f.id] / 100);
      }
      return fam;
    });
    var resources = D.resources.map(function (r) {
      var res = Object.assign({}, r);
      if (levers.hours && levers.hours[r.id] !== undefined) {
        res.monthly_available_hours = levers.hours[r.id];
      }
      return res;
    });
    return { families: families, resources: resources };
  }

  /* ---- recomputeScenario: the full pipeline --------------------------------*/
  function recomputeScenario(D, levers, tag) {
    tag = tag || "custom";
    var mutated = applyLevers(D, levers);
    var families = mutated.families, resources = mutated.resources;
    var rationRule = (levers && levers.rationRule) || "throughput-per-constraint";

    var demandByFm = {};
    families.forEach(function (f) {
      MONTHS.forEach(function (m) {
        demandByFm[f.id + "|" + m] = demandUnits(f, m, tag);
      });
    });
    var loads = computeLoads(families, resources, tag, demandByFm);
    var loadByRm = loadHoursByResourceMonth(loads);
    var plan = buildSupplyPlan(families, resources, tag, rationRule);
    var financeLines = buildFinance(plan.lines, families);
    var summary = summarize(tag, plan.lines, financeLines);
    var monthly = buildMonthly(plan.lines, financeLines);
    var utilization = {};
    resources.forEach(function (r) {
      utilization[r.id] = loads.filter(function (ld) { return ld.resource_id === r.id; })
        .map(function (ld) {
          return { month: ld.month, load_hours: ld.load_hours, available_hours: ld.available_hours, utilization_pct: ld.utilization_pct };
        });
    });
    var reconciliation = buildReconciliation(families, plan.lines, financeLines);
    var provenance = buildProvenance(tag, families, resources, demandByFm, loadByRm, loads, plan.lines, financeLines);

    return {
      scenario: { summary: summary, monthly: monthly, utilization: utilization, reconciliation: reconciliation },
      provenance: provenance,
    };
  }

  return {
    pyRound: pyRound,
    applyLevers: applyLevers,
    demandUnits: demandUnits,
    computeLoads: computeLoads,
    effectiveCapacity: effectiveCapacity,
    allowedUnitsThisMonth: allowedUnitsThisMonth,
    buildSupplyPlan: buildSupplyPlan,
    buildFinance: buildFinance,
    summarize: summarize,
    buildMonthly: buildMonthly,
    buildReconciliation: buildReconciliation,
    buildProvenance: buildProvenance,
    recomputeScenario: recomputeScenario,
  };
});
